/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SW_UP_Pin_aliases.h"
#include "SW_UP_Pin.h"
#include "LED_Pin_aliases.h"
#include "LED_Pin.h"
#include "SW_DOWN_Pin_aliases.h"
#include "SW_DOWN_Pin.h"
#include "SW_LEFT_Pin_aliases.h"
#include "SW_LEFT_Pin.h"
#include "SW_RIGHT_Pin_aliases.h"
#include "SW_RIGHT_Pin.h"
#include "UART.h"
#include "SDA_OLED_aliases.h"
#include "SDA_OLED.h"
#include "SCL_OLED_aliases.h"
#include "SCL_OLED.h"
#include "I2C_OLED.h"
#include "I2C_OLED_PVT.h"
#include "SCL_X_aliases.h"
#include "SCL_X.h"
#include "Clock_2.h"
#include "X_Dir_Pin_aliases.h"
#include "X_Dir_Pin.h"
#include "X_Step_Pin_aliases.h"
#include "X_Step_Pin.h"
#include "MotorControlFallingEdge.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "SDA_X_aliases.h"
#include "SDA_X.h"
#include "MotorControlRiseingEdge.h"
#include "Motor_Enable.h"
#include "timer_clock.h"
#include "Display_Refresh_Timer.h"
#include "Display_Refresh_Timer_Int.h"
#include "I2C_X.h"
#include "I2C_X_PVT.h"
#include "EEPROM_1.h"
#include "SDA_Y_aliases.h"
#include "SDA_Y.h"
#include "SCL_Y_aliases.h"
#include "SCL_Y.h"
#include "Y_Step_Pin_aliases.h"
#include "Y_Step_Pin.h"
#include "I2C_Y.h"
#include "I2C_Y_PVT.h"
#include "Y_Dir_Pin_aliases.h"
#include "Y_Dir_Pin.h"
#include "timer_clock_1.h"
#include "Button_Refresh_Timer.h"
#include "Button_Refresh_Timer_Int.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

